### PR TITLE
Updated for f21 and code cleanup

### PR DESCRIPTION
**Pull request by xfillmore-edu**

### CODE REVIEW

**Comment by Oceanestars** [comment]
Thank you for doing some clean-up and making a lot of changes. Fiona may move the script tag back to the end of the body but I'll let her decide. Where the javascript is imported is highly debated. Putting it inside the body at the end ensures the parser isn't blocked until the very end. But that can cause issues if the HTML page is very long. Since our page isn't very long either is probably fine but  I just wanted to put that comment somewhere.

**Comment by Oceanestars** [comment]
I saw you cleaned some of the CSS. I was wondering if this was on purpose or not, but the navbar doesn't take the full width anymore.

**Comment by xfillmore-edu** [comment]
The CSS cleanup is not substantial; it's a matter of punctuation so that shouldn't have affected the navigation bar. I did just notice that there are attributes assigned to nav in the CSS, and I converted the navigation div on the home page to be an actual nav element. I'm betting this is where issues arose.

**Comment by Oceanestars** [comment]
Oh I see. Thanks!

**Pull request merged**
